### ISSUE TITLE
rockstargames

### ISSUE THREAD

**Issue by codver1** [random-robbie/bugbounty-scans#1]
can you rockstargames.com please

**Comment by random-robbie** [comment]
Please see new site for this

[](https://bugbounty.xsses.rocks)

Ran out of space on github.

**Comment by codver1** [comment]
okay thanks.

**Comment by sydia1103** [comment]
> Please see new site for this
> 
> [(https://bugbounty.xsses.rocks]((https://bugbounty.xsses.rocks)
> 
> Ran out of space on github.

I would just like to notify you that this URL doesn't exist anymore. Is there a new one?
